version: '3.8'

services:
  timesheet-frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://172.169.37.162:8080/api
      - REACT_APP_ENV=production
    restart: unless-stopped
